options:
  dcf_path: "/home/starnus/starnus/starnus_robot_sim/starnus_robot/src/ros2_canopen/install/canopen_tests/share/canopen_tests/config/simple"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"

proxy_device_1:
  node_id: 2
  dcf: "simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  polling: true
  period: 10

proxy_device_2:
  node_id: 3
  dcf: "simple.eds"
  driver: "ros2_canopen::ProxyDriver"
  package: "canopen_proxy_driver"
  polling: true
  period: 10
